application/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crypto/', include('core.urls', namespace="crypto")),
    path('',  IndexView.as_view()),
]

core/urls.py
from django.urls import path
from .views import  EncryptionView, DecryptionView, EncryptionHelpView, DecryptionHelpView, HashingView,\
                    AESEncryptionView, AESDecryptionView, GOSTDecryptionView, GOSTEncryptionView, RSAEncryptionView,\
                    RSADecryptionView, RSAOpenKeyGeneratorView

app_name = 'crypto'
urlpatterns = [
    path('encrypt/help/', EncryptionHelpView.as_view(), name="encrypt_help"),
    path('decrypt/help/', DecryptionHelpView.as_view(), name="decrypt_help"),
    path('hashing/', HashingView.as_view(), name="hashing"),

    path('basic/encrypt/', EncryptionView.as_view(), name="basic_encrypt"),
    path('basic/decrypt/', DecryptionView.as_view(), name="basic_decrypt"),

    path('aes/encrypt/', AESEncryptionView.as_view(), name="aes_encrypt"),
    path('aes/decrypt/', AESDecryptionView.as_view(), name="aes_decrypt"),
    path('gost/encrypt/', GOSTEncryptionView.as_view(), name="gost_encrypt"),
    path('gost/decrypt/', GOSTDecryptionView.as_view(), name="gost_decrypt"),
    path('rsa/encrypt/', RSAEncryptionView.as_view(), name="rsa_encrypt"),
    path('rsa/decrypt/', RSADecryptionView.as_view(), name="rsa_decrypt"),
    path('rsa/generate_open_key/', RSAOpenKeyGeneratorView.as_view(), name="generate_open_key"),
]

core/models.py
from django.db import models

# Create your models here.

backend/core/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from native_lib import crypto_lib, checksum_lib
import json


class EncryptionView(View):
    def get(self, request):
        return render(request, "core/encryption.html")

    def post(self, request):
        form = request.POST
        cipher_algorithm = form.get('encryption_algorithm')
        user_password = form.get('user_password')
        check_sum_algorithm = form.get('check_sum_algorithm')
        msg = form.get('msg')
        context = {
            'text': 'Неверно заполнены поля',
        }
        if msg and user_password and cipher_algorithm:
            result = encrypt(msg, user_password, cipher_algorithm, check_sum_algorithm)
            context = {
                'text': 'Зашифрованное сообщение',
                'msg': result.get('msg'),
                'jsonText': 'JSON для отправки на сервер для расшифрования:',
                'json': result.get('json')
            }

        return render(request, "core/encryption.html", context)


class DecryptionView(View):
    def get(self, request):
        return render(request, "core/decryption.html")

    def post(self, request):
        form = request.POST
        user_password = form.get('user_password')
        msg = json.loads(form.get('msg'))
        print(msg)
        encrypted_data = msg.get('encrypted_data')
        cipher_algorithm = msg.get('cipher_algorithm')
        check_sum_algorithm = msg.get('check_sum_algorithm')
        check_sum_value = msg.get('check_sum_value')
        context = {
            'text': 'Неверный формат введенных данных',
        }

        if encrypted_data and cipher_algorithm and user_password:
            result = decrypt(encrypted_data, user_password, cipher_algorithm, check_sum_algorithm, check_sum_value)
            context = {
                "text": "Результат",
                "msg": result.get('msg'),
                "checked": result.get('checked')
            }

        return render(request, "core/decryption.html", context)


class IndexView(View):
    def get(self, request):
        return render(request, "core/index.html")


class EncryptionHelpView(View):
    def get(self, request):
        return render(request, "core/help_encryption.html")


class DecryptionHelpView(View):
    def get(self, request):
        return render(request, "core/help_decryption.html")


class HashingView(View):
    def get(self, request):
        return render(request, "core/hashing.html")


def encrypt(msg, user_password, cipher_algorithm, check_sum_algorithm):
    encrypted = None
    check_sum = None
    if cipher_algorithm == "Шифр Цезаря":
        encrypted = crypto_lib.get_cesar_encryption(msg, int(user_password))
    elif cipher_algorithm == "Моноалфавитный шифр":
        encrypted = crypto_lib.get_monoalphabetic_encryption(msg, user_password)
    elif cipher_algorithm == "Полиалфавитный шифр":
        encrypted = crypto_lib.get_polyalphabetic_encryption(msg, user_password)
    elif cipher_algorithm == "Биграммный шифр":
        encrypted = crypto_lib.get_bigram_encryption(msg, user_password)

    result = {
        "encrypted_data_codes": encrypted.get('encrypted_character_codes'),
        "encrypted_data": encrypted.get('encrypted_string'),
        "cipher_algorithm": cipher_algorithm,
    }

    if check_sum_algorithm:
        if check_sum_algorithm == "CRC16":
            check_sum = checksum_lib.get_crc16_usb(msg)
        elif check_sum_algorithm == "CRC24":
            check_sum = checksum_lib.get_crc24(msg)
        elif check_sum_algorithm == "CRC32":
            check_sum = checksum_lib.get_crc32(msg)
        elif check_sum_algorithm == "FLETCHER":
            check_sum = checksum_lib.get_fletcher32(msg)
        result["check_sum_value"] = check_sum
        result["check_sum_algorithm"] = check_sum_algorithm

    return {"json": json.dumps(result, indent=4, sort_keys=True, ensure_ascii=False,), "msg": encrypted.get('encrypted_string')}


def decrypt(msg, user_password, cipher_algorithm, check_sum_algorithm, check_sum_value):
    decoded = None
    check_sum_decoded = None

    if cipher_algorithm == "Шифр Цезаря":
        decoded = crypto_lib.get_cesar_decryption(msg, int(user_password)).get('decrypted_string')
    elif cipher_algorithm == "Моноалфавитный шифр":
        decoded = crypto_lib.get_monoalphabetic_decryption(msg, user_password).get('decrypted_string')
    elif cipher_algorithm == "Полиалфавитный шифр":
        decoded = crypto_lib.get_polyalphabetic_decryption(msg, user_password).get('decrypted_string')
    elif cipher_algorithm == "Биграммный шифр":
        decoded = crypto_lib.get_bigram_decryption(msg, user_password).get('decrypted_string')
    result = {
        "msg": decoded
    }
    if check_sum_algorithm:
        if check_sum_algorithm == "CRC16":
            check_sum_decoded = checksum_lib.get_crc16_usb(decoded)
        elif check_sum_algorithm == "CRC24":
            check_sum_decoded = checksum_lib.get_crc24(decoded)
        elif check_sum_algorithm == "CRC32":
            check_sum_decoded = checksum_lib.get_crc32(decoded)
        elif check_sum_algorithm == "FLETCHER":
            check_sum_decoded = checksum_lib.get_fletcher32(decoded)
        result["checked"] = "Совпала" if check_sum_value == check_sum_decoded else "Не совпала"
    return result

core/views.py
from django.shortcuts import render
from django.views import View
from native_lib import crypto_lib, checksum_lib, hash_lib
import json

from native_lib.AES import AES, AES_nodejs
from native_lib.GOST import GOST
from native_lib.RSA import RSA_nodejs


class HashingView(View):
    def get(self, request):
        return render(request, "core/hashing.html")

    def post(self, request):
        form = request.POST
        check_sum_algorithm = form.get('check_sum_algorithm')
        msg = form.get('msg')
        context = {
            'text': 'Неверно заполнены поля',
        }
        if msg and check_sum_algorithm:
            result = hashing(msg, check_sum_algorithm)
            context = {
                'text': 'Ваше сообщение:',
                'msg': form.get('msg'),
                'jsonText': 'Контрольная сумма / Хеш сообщения в формате Json:',
                'json': result.get('json')
            }

        return render(request, "core/hashing.html", context)


class EncryptionView(View):
    def get(self, request):
        return render(request, "core/basic/encrypt.html")

    def post(self, request):
        form = request.POST
        cipher_algorithm = form.get('encryption_algorithm')
        user_password = form.get('user_password')
        check_sum_algorithm = form.get('check_sum_algorithm')
        msg = form.get('msg')
        context = {
            'text': 'Неверно заполнены поля',
        }
        if msg and user_password and cipher_algorithm:
            result = encrypt(msg, user_password, cipher_algorithm, check_sum_algorithm)
            context = {
                'text': 'Зашифрованное сообщение',
                'msg': result.get('msg'),
                'jsonText': 'JSON для отправки на сервер для расшифрования:',
                'json': result.get('json')
            }

        return render(request, "core/basic/encrypt.html", context)


class DecryptionView(View):
    def get(self, request):
        return render(request, "core/basic/decrypt.html")

    def post(self, request):
        form = request.POST
        user_password = form.get('user_password')
        msg = json.loads(form.get('msg'))
        print(msg)
        encrypted_data = msg.get('encrypted_data')
        cipher_algorithm = msg.get('cipher_algorithm')
        check_sum_algorithm = msg.get('check_sum_algorithm')
        check_sum_value = msg.get('check_sum_value')
        context = {
            'text': 'Неверный формат введенных данных',
        }

        if encrypted_data and cipher_algorithm and user_password:
            result = decrypt(encrypted_data, user_password, cipher_algorithm, check_sum_algorithm, check_sum_value)
            context = {
                "text": "Результат",
                "msg": result.get('msg'),
                "checked": result.get('checked')
            }

        return render(request, "core/basic/decrypt.html", context)


class IndexView(View):
    def get(self, request):
        return render(request, "core/index.html")


class EncryptionHelpView(View):
    def get(self, request):
        return render(request, "core/help_encryption.html")


class DecryptionHelpView(View):
    def get(self, request):
        return render(request, "core/help_decryption.html")


def hashing(msg, check_sum_algorithm):
    msg = msg.replace("\r\n", "\n")  # it is necessary to synchronize the work with multiline text on the frontend
    result, check_sum = dict(), dict()
    if check_sum_algorithm == "CRC16":
        check_sum = checksum_lib.get_crc16_modbus(msg)
    elif check_sum_algorithm == "CRC24":
        check_sum = checksum_lib.get_crc24(msg)
    elif check_sum_algorithm == "CRC32":
        check_sum = checksum_lib.get_crc32(msg)
    elif check_sum_algorithm == "FLETCHER":
        check_sum = checksum_lib.get_fletcher16(msg)
    elif check_sum_algorithm == "SHA224":
        check_sum = hash_lib.get_sha224(msg)
    elif check_sum_algorithm == "SHA256":
        check_sum = hash_lib.get_sha256(msg)
    elif check_sum_algorithm == "SHA384":
        check_sum = hash_lib.get_sha384(msg)
    elif check_sum_algorithm == "SHA512":
        check_sum = hash_lib.get_sha512(msg)
    elif check_sum_algorithm == "SHA3_224":
        check_sum = hash_lib.get_sha3_224(msg)
    elif check_sum_algorithm == "SHA3_256":
        check_sum = hash_lib.get_sha3_256(msg)
    elif check_sum_algorithm == "SHA3_384":
        check_sum = hash_lib.get_sha3_384(msg)
    elif check_sum_algorithm == "SHA3_512":
        check_sum = hash_lib.get_sha3_512(msg)
    elif check_sum_algorithm == "SHA3_512_KECCAK":
        check_sum = hash_lib.get_sha3_keccak_512(msg)
    result["check_sum_value"] = check_sum
    result["check_sum_algorithm"] = check_sum_algorithm
    result["message"] = msg

    return {"json": json.dumps(result, indent=4, sort_keys=True, ensure_ascii=False,)}


def encrypt(msg, user_password, cipher_algorithm, check_sum_algorithm):
    msg = msg.replace("\r\n", "\n")  # it is necessary to synchronize the work with multiline text on the frontend
    encrypted = None
    check_sum = None
    if cipher_algorithm == "Цезарь":
        encrypted = crypto_lib.get_cesar_encryption(msg, user_password)
    elif cipher_algorithm == "Моноалфавитный шифр":
        encrypted = crypto_lib.get_monoalphabetic_encryption(msg, user_password)
    elif cipher_algorithm == "Полиалфавитный шифр":
        encrypted = crypto_lib.get_polyalphabetic_encryption(msg, user_password)
    elif cipher_algorithm == "Биграммный шифр":
        encrypted = crypto_lib.get_bigram_encryption(msg, user_password)

    result = {
        "encrypted_data_codes": encrypted.get('encrypted_character_codes'),
        "encrypted_data": encrypted.get('encrypted_string'),
        "cipher_algorithm": cipher_algorithm,
    }

    if check_sum_algorithm:
        if check_sum_algorithm == "CRC16":
            check_sum = checksum_lib.get_crc16_usb(msg)
        elif check_sum_algorithm == "CRC24":
            check_sum = checksum_lib.get_crc24(msg)
        elif check_sum_algorithm == "CRC32":
            check_sum = checksum_lib.get_crc32(msg)
        elif check_sum_algorithm == "FLETCHER":
            check_sum = checksum_lib.get_fletcher16(msg)
        result["check_sum_value"] = check_sum
        result["check_sum_algorithm"] = check_sum_algorithm

    return {"json": json.dumps(result, indent=4, sort_keys=True, ensure_ascii=False,), "msg": encrypted.get('encrypted_string')}


def decrypt(msg, user_password, cipher_algorithm, check_sum_algorithm, check_sum_value):
    decoded = None
    check_sum_decoded = None

    if cipher_algorithm == "Цезарь":
        decoded = crypto_lib.get_cesar_decryption(msg, user_password).get('decrypted_string')
    elif cipher_algorithm == "Моноалфавитный шифр":
        decoded = crypto_lib.get_monoalphabetic_decryption(msg, user_password).get('decrypted_string')
    elif cipher_algorithm == "Полиалфавитный шифр":
        decoded = crypto_lib.get_polyalphabetic_decryption(msg, user_password).get('decrypted_string')
    elif cipher_algorithm == "Биграммный шифр":
        decoded = crypto_lib.get_bigram_decryption(msg, user_password).get('decrypted_string')
    result = {
        "msg": decoded
    }
    if check_sum_algorithm:
        if check_sum_algorithm == "CRC16":
            check_sum_decoded = checksum_lib.get_crc16_usb(decoded)
        elif check_sum_algorithm == "CRC24":
            check_sum_decoded = checksum_lib.get_crc24(decoded)
        elif check_sum_algorithm == "CRC32":
            check_sum_decoded = checksum_lib.get_crc32(decoded)
        elif check_sum_algorithm == "FLETCHER":
            check_sum_decoded = checksum_lib.get_fletcher16(decoded)
        result["checked"] = "Совпала" if check_sum_value == check_sum_decoded else "Не совпала"
    return result


class AESEncryptionView(View):
    def get(self, request):
        return render(request, "core/aes/encrypt.html")

    def post(self, request):
        data = request.POST

        secret = data.get('secret')
        mode = data.get('mode')
        text = data.get('text')

        text = text.replace("\r\n", "\n")  # it is necessary to synchronize the work with multiline text on the frontend

        if not secret or not mode or not text:
            context = {
                'error': 'Заполните все поля...'
            }
            return render(request, "core/aes/encrypt.html", context)

        if mode == "aes256ecb":
            encrypted_result = AES_nodejs.get_aes256ecb_encryption_from_nodejs_server(text, secret)
            result = {
                'encrypted_data': encrypted_result["encrypted_data"].decode("utf-8"),
                'cipher_algorithm': 'AES-256/ECB',
                'initialization_vector': "void for ECB",
            }

        if mode == "aes256cbc":
            encrypted_result = AES_nodejs.get_aes256cbc_encryption_from_nodejs_server(text, secret)
            result = {
                'encrypted_data': json.loads(encrypted_result)["encrypted_data"],
                'cipher_algorithm': 'AES-256/CBC',
                'initialization_vector': json.loads(encrypted_result)["user_iv"],
            }

        if mode == "aes256ctr":
            encrypted_result = AES_nodejs.get_aes256ctr_encryption_from_nodejs_server(text, secret)
            result = {
                'encrypted_data': encrypted_result["encrypted_data"].decode("utf-8"),
                'cipher_algorithm': 'AES-256/CTR',
                'initialization_vector': "void for CTR",
            }

        if mode == "aes256cfb":
            encrypted_result = AES_nodejs.get_aes256cfb_encryption_from_nodejs_server(text, secret)
            result = {
                'encrypted_data': json.loads(encrypted_result)["encrypted_data"],
                'cipher_algorithm': 'AES-256/CFB',
                'initialization_vector': json.loads(encrypted_result)["user_iv"],
            }

        if mode == "aes256ofb":

core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="/">ISP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          BASIC
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url "crypto:basic_encrypt" %}">Шифрование</a>
                          <a class="dropdown-item" href="{% url 'crypto:basic_decrypt' %}">Расшифрование</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          AES
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'crypto:aes_encrypt' %}">Шифрование</a>
                          <a class="dropdown-item" href="{% url 'crypto:aes_decrypt' %}">Дешифрование</a>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'crypto:hashing' %}">Хэширование и CRC</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          GOST
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'crypto:gost_encrypt' %}">Шифрование</a>
                          <a class="dropdown-item" href="{% url 'crypto:gost_decrypt' %}">Дешифрование</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          RSA
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'crypto:rsa_encrypt' %}">Шифрование</a>
                          <a class="dropdown-item" href="{% url 'crypto:rsa_decrypt' %}">Расшифрование</a>
                          <a class="dropdown-item" href="{% url 'crypto:generate_open_key' %}">Генерация открытого ключа</a>
                        </div>
                    </li>
                </ul>
            </div>

        </nav>
        <div class="container">
            {% block main %}{% endblock %}
        </div>
    </body>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

core/templates/core/hashing.html
{% extends "core/base.html" %}

{% block title %}Hashing{% endblock %}

{% block main %}
    <div>
        <h1 class="mt-3">Хэширование и контрольные суммы</h1>
        <form action="{% url 'crypto:hashing' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputCRC">Алгоритм вычисления контрольной суммы:</label>
                <select name="check_sum_algorithm" id="inputCRC" class="form-control" required>
                    <option disabled selected>Выберите алгоритм...</option>
                    <option value="CRC16">CRC16 (modbus)</option>
                    <option value="CRC24">CRC24</option>
                    <option value="CRC32">CRC32</option>
                    <option value="FLETCHER">FLETCHER</option>
                    <option value="SHA224">SHA224</option>
                    <option value="SHA256">SHA256</option>
                    <option value="SHA384">SHA384</option>
                    <option value="SHA512">SHA512</option>
                    <option value="SHA3_224">SHA3_224</option>
                    <option value="SHA3_256">SHA3_256</option>
                    <option value="SHA3_384">SHA3_384</option>
                    <option value="SHA3_512">SHA3_512</option>
                    <option value="SHA3_512_KECCAK">SHA3_512_KECCAK</option>
                </select>
            </div>
            <div class="form-group">
                <label for="inputText">Текст:</label>
                <textarea name="msg" rows="12" class="form-control" id="inputText" placeholder="Напишите текст для вычисления..." required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Вычислить</button>
        </form>

        <div class="text"> {{ text }} </div>
        <div class="msg"> <pre><code>{{ msg }} </pre></code> </div>
        <div class="text"> {{ jsonText }}</div>
        <pre class="json"> {{ json }} </pre>
    </div>
{% endblock %}

core/templates/core/help_decryption.html
{% extends "core/base.html" %}

{% block title %}Help decryption{% endblock %}

{% block main %}
    <h1>Пользовательский манаул по расшифрованию с примерами</h1>
{% endblock %}

core/templates/core/help_encryption.html
{% extends "core/base.html" %}

{% block title %}Help encryption{% endblock %}

{% block main %}
    <h1>Пользовательский манаул по шифрованию с примерами</h1>
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Information Security Project (ISP){% endblock %}

{% block main %}
    <h1 class="mt-3">Главная страница Information Security Project (ISP)</h1>
    <p>Ищите нас на <a href="https://github.com/GRISHNOV/Information_Security_Web_Service/" target="_blank">github</a></p>
{% endblock %}